DROP TABLE IF EXISTS arquivos;

CREATE TABLE arquivos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    caminho TEXT NOT NULL,
    content TEXT NOT NULL
);